In [1]:
data = [10,20,30,40]

In [2]:
# int float values
import numpy as np

In [3]:
a = np.array(data) # array
a

array([10, 20, 30, 40])

In [4]:
# Q.list vs numpy array


In [5]:
# what type of numpy array
type(a)

numpy.ndarray

In [6]:
# to genarate array an squnce of numbers
np.arange(24) #stop

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
np.arange(2,11) # start,stop

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,21,2) #start,stop,step

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#ans this que
a[::2]

In [10]:
# lets create an array with 24 numbers
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
# 2D-rows,columns
s=np.arange(24).reshape(4,6)
s

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
#lets cheak properties of array
s.ndim

2

In [15]:
# count of Rows,columns
s.shape

(4, 6)

In [16]:
s.size

24

In [18]:
print(s.sum())

276


In [20]:
s.max()

np.int64(23)

In [21]:
s.min()

np.int64(0)

In [22]:
s.mean()

np.float64(11.5)

In [23]:
s

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
d=np.array([[ 0,  1,  2,  3,],
       [ 6,  7,  8,  9,],
       [12, 13, 14, 15,],
       [18, 19, 20, 21,]])
d

array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21]])

In [36]:
# for temp change
s.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [38]:
# for permenent changes
s.resize(2,12)

In [39]:
# convert Rows into column
s.T


array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])

In [40]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [41]:
# Row wise addition
s.sum(axis=1)

array([ 66, 210])

In [42]:
# colum wise addition
s.sum(axis=0)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])