In [1]:
import numpy as np

**indexing and slicing**

In [7]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
# indexing work on rows intially
x[0]

array([0, 1, 2, 0])

In [9]:
x[-1]

array([12, 13, 14, 15])

In [15]:
# select 14 from last row
x[-1,2]

np.int64(14)

In [13]:
x[-1][3]

np.int64(15)

In [ ]:
x[:,:] #[row ,column]

In [18]:
x[: , :2] # start:stop

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [19]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
#13,14
x[-1:,1:3]

array([[13, 14]])

In [30]:
#2,3
#10,11
x[::2,2:]

array([[ 2,  3],
       [10, 11]])

In [31]:
x.diagonal()

array([ 0,  5, 10, 15])

In [32]:
# select corner element of an array
x[::3,::3]

array([[ 0,  3],
       [12, 15]])

In [34]:
# replace corner element by 0
x[::3,::3]=0
x

array([[ 0,  1,  2,  0],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0, 13, 14,  0]])

In [36]:
# 1D array
np.random.random(5)

array([0.06707615, 0.05411034, 0.91200188, 0.56492427, 0.70106013])

In [35]:
# 2D array
np.random.random((5,5))

array([[0.01525062, 0.03819331, 0.84007019, 0.35533381, 0.39161234],
       [0.85455629, 0.4887811 , 0.1750453 , 0.38023813, 0.39151054],
       [0.11804072, 0.61134923, 0.01381315, 0.70283452, 0.2841351 ],
       [0.16618575, 0.83557953, 0.36864699, 0.69401988, 0.53427297],
       [0.20758019, 0.41038049, 0.0378768 , 0.4507049 , 0.55546411]])

In [ ]:
# 3D array
np.random.random((3,2,2)) #(block,row,column)

In [37]:
p=np.random.random((5,5))
p

array([[0.35079489, 0.83372713, 0.85174701, 0.04691314, 0.55011662],
       [0.77650191, 0.67696678, 0.80886442, 0.85888087, 0.80346199],
       [0.46739367, 0.29477935, 0.6596602 , 0.8456861 , 0.04047101],
       [0.91128997, 0.43700309, 0.29734832, 0.69889067, 0.79618637],
       [0.47679512, 0.83231035, 0.25019271, 0.61124527, 0.11720024]])

In [40]:
# delete any row
np.delete(p,1,0) # (arr,index,axis)

array([[0.35079489, 0.83372713, 0.85174701, 0.04691314, 0.55011662],
       [0.46739367, 0.29477935, 0.6596602 , 0.8456861 , 0.04047101],
       [0.91128997, 0.43700309, 0.29734832, 0.69889067, 0.79618637],
       [0.47679512, 0.83231035, 0.25019271, 0.61124527, 0.11720024]])